> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Numpy Package


### Numpy is used to perform various mathematical operations.

Write a short introduction about Numpy and list the chosen functions. 

- np.concatenate
- np.sum
- np.matmul
- np.max
- np.reshape

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [1]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.concatenate  # (change this)
function2 = np.sum
function3 = np.matmul
function4 = np.max
function5 = np.reshape

## Function 1 - np.concatenate

This is used to join two arrays either column wise or row wise.

In [6]:
# Example 1 - working
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

In [7]:
# Example 2 - working
arr1 = [[1, 2], 
        [3, 4]]

arr2 = [[5, 6], 
        [8, 9]]

np.concatenate((arr1, arr2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 9]])

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

## Function 2 - np.sum

It is used to sum the elements.

In [9]:
# Example 1 - working
arr1 = np.array([1, 2, 3, 4])
np.sum(arr1)

10

In [17]:
# Example 2 - working
arr1 = np.array([[1, 2], 
        [3, 4]])

arr2 = np.array([[5, 6], 
        [8, 9]])

np.sum((arr1,arr2),axis=1)

array([[ 4,  6],
       [13, 15]])

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[1, 2], 
        [3, 4]])

arr2 = np.array([[5, 6, 7], 
        [8, 9, 10]])

np.sum((arr1,arr2),axis=1)

/srv/conda/envs/notebook/lib/python3.8/site-packages/numpy/core/fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


ValueError: could not broadcast input array from shape (2,2) into shape (2)

## Function 3 - np.matmul

It returns the matrix product of two arrays.

In [19]:
# Example 1 - working
arr1 = np.array([[1, 2], 
        [3, 4]])

arr2 = np.array([[5, 6], 
        [8, 9]])

np.matmul(arr1,arr2)

array([[21, 24],
       [47, 54]])

In [23]:
# Example 2 - working
arr1 = np.array([[1, 2], 
        [3, 4]])

arr2 = np.array([[5, 6, 7], 
        [8, 9, 10]])

np.matmul(arr1,arr2)

array([[21, 24, 27],
       [47, 54, 61]])

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[1, 2], 
        [3, 4]])

arr2 = np.array([[5, 6, 7], 
        [8, 9, 10]])

np.matmul((arr1,arr2),axis=1)

ValueError: invalid number of arguments

## Function 4 - np.max

It is used to find the maximum value in the array.

In [25]:
# Example 1 - working
arr = np.array([1, 2, 3, 5, 10])
np.max(arr)

10

In [28]:
# Example 2 - working
arr1 = np.array([[2, 78, 34, 54],
                [9, 23, 45, 87],
                [4, 9, 76, 54]])

np.max(arr1)

87

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([2, 78, 34, 54],
                [9, 23, 45, 87],
                [4, 9, 76, 54])
np.max(arr1)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

## Function 5 - np.reshape

It is used to reshape the array uinto rows and columns.

In [33]:
# Example 1 - working
arr1 = np.array([1, 3, 8, 6, 0, 7]).reshape(2,3)
arr1

array([[1, 3, 8],
       [6, 0, 7]])

In [34]:
# Example 2 - working
arr1 = np.arange(8).reshape(2,4)
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [37]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[2, 4, 6, 8, 10],
                [12, 14, 16, 18, 20]]).reshape(3,2)
arr1

ValueError: cannot reshape array of size 10 into shape (3,2)